// =============================================================================
// ARNOLD — Health + AI Disclaimer Modal
// Blocking overlay shown once per device during onboarding, before plan
// generation. Same copy is reused (static) in Settings → About → Disclaimers.
// Spec ref: v2.4.6 amendment, Change 1. Apple guidelines 1.4.1 + 5.1.1(ix).
// AsyncStorage only — no schema, no migration.
// =============================================================================

import React, { useState } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Modal,
  ActivityIndicator,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { colors, typography, spacing, radius } from "../theme";

// ── Copy + storage constants (single source of truth) ────────────────────────

export const DISCLAIMER_ASYNC_STORAGE_KEY = 'arnold.disclaimerAcknowledgedAt';

export const DISCLAIMER_TITLE = 'Before you start.';

export const DISCLAIMER_PARAGRAPH_1 =
  "Arnold designs training plans and prescribes weights, reps, and exercises. " +
  "Consult a physician before starting any exercise program — especially if you have " +
  "an injury, medical condition, or haven't trained recently. Stop training and seek " +
  "medical attention if you experience pain, dizziness, or unusual discomfort. " +
  "Arnold is not a substitute for medical advice.";

export const DISCLAIMER_PARAGRAPH_2 =
  "Arnold's coaching responses, plan adjustments, and chat replies are generated by AI. " +
  "They reflect coaching principles encoded in the app, not the judgment of a licensed " +
  "human coach. For complex medical or rehabilitation situations, work with a qualified " +
  "professional.";

// ── Helpers ──────────────────────────────────────────────────────────────────

export async function hasAcknowledgedDisclaimer(): Promise<boolean> {
  const v = await AsyncStorage.getItem(DISCLAIMER_ASYNC_STORAGE_KEY);
  return v !== null;
}

export async function acknowledgeDisclaimer(): Promise<void> {
  await AsyncStorage.setItem(DISCLAIMER_ASYNC_STORAGE_KEY, new Date().toISOString());
}

// ── Component ────────────────────────────────────────────────────────────────

interface DisclaimerModalProps {
  visible: boolean;
  onAcknowledge: () => void;
}

export default function DisclaimerModal({ visible, onAcknowledge }: DisclaimerModalProps) {
  const insets = useSafeAreaInsets();
  const [saving, setSaving] = useState(false);

  const handlePress = async () => {
    if (saving) return;
    setSaving(true);
    try {
      await acknowledgeDisclaimer();
    } finally {
      setSaving(false);
      onAcknowledge();
    }
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      statusBarTranslucent
      // Intercept Android hardware back — modal is blocking, no dismissal.
      onRequestClose={() => {}}
    >
      <View
        style={[
          styles.container,
          {
            paddingTop: insets.top + spacing.xl,
            paddingBottom: insets.bottom + spacing.lg,
          },
        ]}
      >
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          <Text style={styles.title}>{DISCLAIMER_TITLE}</Text>
          <Text style={styles.paragraph}>{DISCLAIMER_PARAGRAPH_1}</Text>
          <Text style={styles.paragraph}>{DISCLAIMER_PARAGRAPH_2}</Text>
        </ScrollView>

        <TouchableOpacity
          style={[styles.button, saving && styles.buttonDisabled]}
          onPress={handlePress}
          disabled={saving}
          activeOpacity={0.85}
        >
          {saving ? (
            <ActivityIndicator color={colors.bg} />
          ) : (
            <Text style={styles.buttonText}>I understand — let's start</Text>
          )}
        </TouchableOpacity>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
    paddingHorizontal: spacing.lg,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
  },
  title: {
    fontSize: typography.sizes.xl,
    fontWeight: "800",
    color: colors.text,
    marginBottom: spacing.lg,
  },
  paragraph: {
    fontSize: typography.sizes.base,
    color: colors.textSecondary,
    lineHeight: 23,
    marginBottom: spacing.lg,
  },
  button: {
    height: 56,
    borderRadius: radius.md,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    fontSize: typography.sizes.md,
    fontWeight: "800",
    color: colors.bg,
  },
});
